installer changes and fixes

diff --git a/usr/bin/holoiso_getlatest b/usr/bin/holoiso_getlatest
--- a/usr/bin/holoiso_getlatest
+++ b/usr/bin/holoiso_getlatest
@@ -15,7 +15,15 @@ if [ "$(cat /etc/installer_type)" == "online" ]; then
     sudo wget $LATEST_URL -O /etc/holoinstall/latest_$BRANCH.releasemeta
     source /etc/holoinstall/latest_$BRANCH.releasemeta
     echo $IMAGEFILE
-    sudo wget "${MIRROR}/holoiso-images/$BRANCH/${IMAGEFILE}.img.zst" -O "/etc/holoinstall/${IMAGEFILE}.img.zst"
-    sudo wget "${MIRROR}/holoiso-images/$BRANCH/${IMAGEFILE}.sha256" -O "/etc/holoinstall/${IMAGEFILE}.sha256"
+    sudo holoiso_gui_download "${MIRROR}/holoiso-images/$BRANCH/${IMAGEFILE}.img.zst" "/etc/holoinstall/${IMAGEFILE}.img.zst"
+    sudo holoiso_gui_download "${MIRROR}/holoiso-images/$BRANCH/${IMAGEFILE}.sha256" "/etc/holoinstall/${IMAGEFILE}.sha256"
+
+    # verify img.zst sha256 and the downloaded sha256 file are the same
+    sha256sum -c /etc/holoinstall/${IMAGEFILE}.sha256
+    if [ $? -ne 0 ]; then
+        kdialog --error "Checksum verification failed for the downloaded HoloISO image. The installation cannot proceed."
+        exit 1
+    fi
+
 fi
-holoiso_installer_gui
+holoiso_gui_installer
